mongo:
  image: mongo:3.2

orion:
  image: telefonicaiot/fiware-orion:develop
  links:
    - mongo
  ports:
    - "10026:1026"
  command: -dbhost mongo

mysql:
  image: mysql:5.5  
  expose:
    - "3306"
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: iotonpremise
    MYSQL_DATABASE: keypass
    MYSQL_USER: keypass
    MYSQL_PASSWORD: keypass

keypass:
  image: telefonicaiot/fiware-keypass:develop
  links:
    - mysql
  expose:
    - "17070"
    - "7071"
  ports:
    - "17070:7070"
    - "7071:7071"
  command: -dbhost mysql

keystone:
  image: telefonicaiot/fiware-keystone-spassword:develop
  expose:
    - "5001"
  links:
    - mysql
  ports:
    - "5001:5001"
  command: -dbhost mysql -default_pwd 4pass1w0rd -mysql_pwd iotonpremise

orchestrator:
  image: telefonicaiot/orchestrator:develop
  expose:
    - "8084"
  links:
    - keystone
    - keypass
    - orion
  ports:
    - "8084:8084"
  command: -keystonehost keystone -keypasshost keypass -orionhost orion

portal:
  image: telefonicaiot/portal:develop
  links:
    - keystone
    - orion
    - orchestrator
  ports:
    - "80:80"
    - "8008:8008"
    - "443:443"
  environment:
    - portal_hostname=my_iot_portal
  command: -urlcep localhost:9090 -urlidm keystone:5001 -urlcb orion:1026 -urlorc orchestrator:8084 -urliot localhost:8081 -urlsth localhost:8666
